using REngine.Core.IO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace REngine.WindowsGtk
{
	public static class InputConverter
	{
		private static readonly Dictionary<Gdk.Key, InputKey> sKeys = new Dictionary<Gdk.Key, InputKey>
		{
			{ Gdk.Key.BackSpace,	InputKey.Backspace },
			{ Gdk.Key.Tab,			InputKey.Tab },
			{ Gdk.Key.Linefeed,		InputKey.LineFeed },
			{ Gdk.Key.Clear,		InputKey.Clear },
			{ Gdk.Key.Return,		InputKey.Return },
			{ Gdk.Key.Pause,		InputKey.Pause },
			{ Gdk.Key.Scroll_Lock,	InputKey.Scroll },
			{ Gdk.Key.Escape,		InputKey.Esc },
			{ Gdk.Key.Delete,		InputKey.Delete },
			{ Gdk.Key.Home,			InputKey.Home },
			{ Gdk.Key.Left,			InputKey.Left },
			{ Gdk.Key.Up,			InputKey.Up },
			{ Gdk.Key.Right,		InputKey.Right },
			{ Gdk.Key.Down,			InputKey.Down },
			{ Gdk.Key.Page_Up,		InputKey.PageUp },
			{ Gdk.Key.Page_Down,	InputKey.PageDown },
			{ Gdk.Key.End,			InputKey.End },
			{ Gdk.Key.Select,		InputKey.Select },
			{ Gdk.Key.Print,		InputKey.Print },
			{ Gdk.Key.Execute,		InputKey.Execute },
			{ Gdk.Key.Insert,		InputKey.Insert },
			{ Gdk.Key.Menu,			InputKey.Menu },
			{ Gdk.Key.Find,			InputKey.BrowserSearch },
			{ Gdk.Key.Cancel,		InputKey.Esc },
			{ Gdk.Key.Help,			InputKey.Help },
			{ Gdk.Key.Num_Lock,		InputKey.NumLock },
			{ Gdk.Key.KP_Space,		InputKey.Space },
			{ Gdk.Key.KP_Tab,		InputKey.Tab },
			{ Gdk.Key.KP_Enter,		InputKey.Enter },
			{ Gdk.Key.KP_Home,		InputKey.Home },
			{ Gdk.Key.KP_Left,		InputKey.Left },
			{ Gdk.Key.KP_Up,		InputKey.Up },
			{ Gdk.Key.KP_Right,		InputKey.Right },
			{ Gdk.Key.KP_Down,		InputKey.Down },
			{ Gdk.Key.KP_Page_Up,	InputKey.PageUp },
			{ Gdk.Key.KP_Page_Down, InputKey.PageDown },
			{ Gdk.Key.KP_End,		InputKey.End },
			{ Gdk.Key.KP_Insert,	InputKey.Insert },
			{ Gdk.Key.KP_Decimal,	InputKey.Delete },
			{ Gdk.Key.KP_Divide,	InputKey.Divide },
			{ Gdk.Key.KP_0,			InputKey.NumPad0 },
			{ Gdk.Key.KP_1,			InputKey.NumPad1 },
			{ Gdk.Key.KP_2,			InputKey.NumPad2 },
			{ Gdk.Key.KP_3,			InputKey.NumPad3 },
			{ Gdk.Key.KP_4,			InputKey.NumPad4 },
			{ Gdk.Key.KP_5,			InputKey.NumPad5 },
			{ Gdk.Key.KP_6,			InputKey.NumPad6 },
			{ Gdk.Key.KP_7,			InputKey.NumPad7 },
			{ Gdk.Key.KP_8,			InputKey.NumPad8 },
			{ Gdk.Key.KP_9,			InputKey.NumPad9 },
			{ Gdk.Key.F1,			InputKey.F1 },
			{ Gdk.Key.F2,			InputKey.F2 },
			{ Gdk.Key.F3,			InputKey.F3 },
			{ Gdk.Key.F4,			InputKey.F4 },
			{ Gdk.Key.F5,			InputKey.F5 },
			{ Gdk.Key.F6,			InputKey.F6 },
			{ Gdk.Key.F7,			InputKey.F7 },
			{ Gdk.Key.F8,			InputKey.F8 },
			{ Gdk.Key.F9,			InputKey.F9 },
			{ Gdk.Key.F10,			InputKey.F10 },
			{ Gdk.Key.F11,			InputKey.F11 },
			{ Gdk.Key.F12,			InputKey.F12 },
			{ Gdk.Key.F13,			InputKey.F13 },
			{ Gdk.Key.F14,			InputKey.F14 },
			{ Gdk.Key.F15,			InputKey.F15 },
			{ Gdk.Key.F16,			InputKey.F16 },
			{ Gdk.Key.F17,			InputKey.F17 },
			{ Gdk.Key.F18,			InputKey.F18 },
			{ Gdk.Key.F19,			InputKey.F19 },
			{ Gdk.Key.F20,			InputKey.F20 },
			{ Gdk.Key.F21,			InputKey.F21 },
			{ Gdk.Key.F22,			InputKey.F22 },
			{ Gdk.Key.F23,			InputKey.F23 },
			{ Gdk.Key.F24,			InputKey.F24 },
			{ Gdk.Key.Shift_L,		InputKey.LeftShift },
			{ Gdk.Key.Shift_R,		InputKey.RightShift },
			{ Gdk.Key.Caps_Lock,	InputKey.Capslock },
			{ Gdk.Key.Meta_L,		InputKey.LeftAlt },
			{ Gdk.Key.Meta_R,		InputKey.RightAlt },
			{ Gdk.Key.Alt_L,		InputKey.LeftAlt },
			{ Gdk.Key.Alt_R,		InputKey.RightAlt },
			{ Gdk.Key.Super_L,		InputKey.LeftSuper },
			{ Gdk.Key.Super_R,		InputKey.RightSuper },
			{ Gdk.Key.Hyper_L,		InputKey.LeftControl },
			{ Gdk.Key.Hyper_R,		InputKey.RightControl },
			{ Gdk.Key.space,		InputKey.Space },
			{ Gdk.Key.exclam,		InputKey.D1 },
			{ Gdk.Key.quotedbl,		InputKey.Quotes },
			{ Gdk.Key.numbersign,	InputKey.D3 },
			{ Gdk.Key.dollar,		InputKey.D4 },
			{ Gdk.Key.percent,		InputKey.D5 },
			{ Gdk.Key.ampersand,	InputKey.D2 },
			{ Gdk.Key.apostrophe,	InputKey.D6 },
			{ Gdk.Key.parenleft,	InputKey.D9 },
			{ Gdk.Key.parenright,	InputKey.D0 },
			{ Gdk.Key.asterisk,		InputKey.D8 },
			{ Gdk.Key.plus,			InputKey.Plus },
			{ Gdk.Key.comma,		InputKey.Comma },
			{ Gdk.Key.minus,		InputKey.Minus },
			{ Gdk.Key.period,		InputKey.Period },
			{ Gdk.Key.slash,		InputKey.Pipe },
			{ Gdk.Key.Key_0,		InputKey.D0 },
			{ Gdk.Key.Key_1,		InputKey.D1 },
			{ Gdk.Key.Key_2,		InputKey.D2 },
			{ Gdk.Key.Key_3,		InputKey.D3 },
			{ Gdk.Key.Key_4,		InputKey.D4 },
			{ Gdk.Key.Key_5,		InputKey.D5 },
			{ Gdk.Key.Key_6,		InputKey.D6 },
			{ Gdk.Key.Key_7,		InputKey.D7 },
			{ Gdk.Key.Key_8,		InputKey.D8 },
			{ Gdk.Key.Key_9,		InputKey.D9 },
			{ Gdk.Key.colon,		InputKey.Semicolon },
			{ Gdk.Key.semicolon,	InputKey.Semicolon },
			{ Gdk.Key.less,			InputKey.Comma },
			{ Gdk.Key.equal,		InputKey.Plus },
			{ Gdk.Key.greater,		InputKey.Period },
			{ Gdk.Key.question,		InputKey.Question },
			{ Gdk.Key.at,			InputKey.D2 },
			{ Gdk.Key.A,			InputKey.A },
			{ Gdk.Key.B,			InputKey.B },
			{ Gdk.Key.C,			InputKey.C },
			{ Gdk.Key.D,			InputKey.D },
			{ Gdk.Key.E,			InputKey.E },
			{ Gdk.Key.F,			InputKey.F },
			{ Gdk.Key.G,			InputKey.G },
			{ Gdk.Key.H,			InputKey.H },
			{ Gdk.Key.I,			InputKey.I },
			{ Gdk.Key.J,			InputKey.J },
			{ Gdk.Key.K,			InputKey.K },
			{ Gdk.Key.L,			InputKey.L },
			{ Gdk.Key.M,			InputKey.M },
			{ Gdk.Key.N,			InputKey.N },
			{ Gdk.Key.O,			InputKey.O },
			{ Gdk.Key.P,			InputKey.P },
			{ Gdk.Key.Q,			InputKey.Q },
			{ Gdk.Key.R,			InputKey.R },
			{ Gdk.Key.S,			InputKey.S },
			{ Gdk.Key.T,			InputKey.T },
			{ Gdk.Key.U,			InputKey.U },
			{ Gdk.Key.V,			InputKey.V },
			{ Gdk.Key.W,			InputKey.W },
			{ Gdk.Key.X,			InputKey.X },
			{ Gdk.Key.Y,			InputKey.Y },
			{ Gdk.Key.Z,			InputKey.Z },
			{ Gdk.Key.bracketleft,	InputKey.OpenBrackets },
			{ Gdk.Key.backslash,	InputKey.Backslash },
			{ Gdk.Key.bracketright, InputKey.CloseBrackets },
			{ Gdk.Key.caret,		InputKey.Tilde },
			{ Gdk.Key.underscore,	InputKey.Minus },
			{ Gdk.Key.grave,		InputKey.Tilde },
			{ Gdk.Key.a,			InputKey.A },
			{ Gdk.Key.b,			InputKey.B },
			{ Gdk.Key.c,			InputKey.C },
			{ Gdk.Key.d,			InputKey.D },
			{ Gdk.Key.e,			InputKey.E },
			{ Gdk.Key.f,			InputKey.F },
			{ Gdk.Key.g,			InputKey.G },
			{ Gdk.Key.h,			InputKey.H },
			{ Gdk.Key.i,			InputKey.I },
			{ Gdk.Key.j,			InputKey.J },
			{ Gdk.Key.k,			InputKey.K },
			{ Gdk.Key.l,			InputKey.L },
			{ Gdk.Key.m,			InputKey.M },
			{ Gdk.Key.n,			InputKey.N },
			{ Gdk.Key.o,			InputKey.O },
			{ Gdk.Key.p,			InputKey.P },
			{ Gdk.Key.q,			InputKey.Q },
			{ Gdk.Key.r,			InputKey.R },
			{ Gdk.Key.s,			InputKey.S },
			{ Gdk.Key.t,			InputKey.T },
			{ Gdk.Key.u,			InputKey.U },
			{ Gdk.Key.v,			InputKey.V },
			{ Gdk.Key.w,			InputKey.W },
			{ Gdk.Key.x,			InputKey.X },
			{ Gdk.Key.y,			InputKey.Y },
			{ Gdk.Key.z,			InputKey.Z },
			{ Gdk.Key.braceleft,	InputKey.OpenBrackets },
			{ Gdk.Key.bar,			InputKey.Pipe },
			{ Gdk.Key.braceright,	InputKey.CloseBrackets },
			{ Gdk.Key.asciitilde,	InputKey.Tilde },
			{ Gdk.Key.Control_L,	InputKey.LeftControl },
			{ Gdk.Key.Control_R,	InputKey.RightControl },
		};

		private static readonly MouseKey[] sMouseKeys = new MouseKey[] 
		{
			MouseKey.None,
			MouseKey.Left,
			MouseKey.Middle,
			MouseKey.Right,
			MouseKey.None,
			MouseKey.None,
			MouseKey.None,
			MouseKey.None,
			MouseKey.XButton1,
			MouseKey.XButton2,
		};

		public static InputKey GetKeys(Gdk.Key key)
		{
			if(sKeys.TryGetValue(key, out InputKey result))
				return result;
			return InputKey.None;
		}

		public static MouseKey GetMouseKey(uint button)
		{
			return sMouseKeys[button];
		}
	}
}
