#pragma once
#include "./defines.h"

#define VERTEX_ELEMENT_POSITION_IDX		0
#define VERTEX_ELEMENT_NORMAL_IDX		1
#define VERTEX_ELEMENT_TANGENT_IDX		2
#define VERTEX_ELEMENT_COLOR_IDX		3
#define VERTEX_ELEMENT_COLORF_IDX		4
#define VERTEX_ELEMENT_UV_IDX			5
#define VERTEX_ELEMENT_INSTANCING_IDX	6
#define VERTEX_ELEMENT_COUNT			7